### ISSUE TITLE
GeneSys.arch not opened yet?

### ISSUE THREAD

**Issue by cnjsdfcy** [actlab-genesys/GeneSys#4]
Hi,

Any plan to open the https://github.com/actlab-genesys/GeneSys.arch/tree/d9927d5acc00c038e11ddb306ab90090a5a4766f ?

Thanks,
Cai Yu

**Comment by christopherpriebe** [comment]
Hey. Please fill out [this form](https://forms.gle/Co7YBvS9YFuTrNzg7) if you are interested in accessing the GeneSys RTL files or the GeneSys compiler code.
